# Generated by Django 4.1.5 on 2023-01-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unixTimestamp', models.DecimalField(decimal_places=7, max_digits=18)),
                ('timestamp', models.DateTimeField(verbose_name='time submitted')),
                ('lightLevel', models.IntegerField()),
                ('isMotion', models.BooleanField(verbose_name='motion present')),
            ],
        ),
    ]
