# Generated by Django 4.1.5 on 2023-01-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_entry',
            name='isMotion',
        ),
        migrations.RemoveField(
            model_name='data_entry',
            name='lightLevel',
        ),
        migrations.RemoveField(
            model_name='data_entry',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='data_entry',
            name='unixTimestamp',
        ),
        migrations.AddField(
            model_name='data_entry',
            name='endTime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='data_entry',
            name='startTime',
            field=models.DateTimeField(default=None),
        ),
    ]
