# Generated by Django 4.1.6 on 2023-02-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region',
            new_name='SettingsData',
        ),
    ]
