# Generated by Django 4.1.6 on 2023-02-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_monitoring', '0002_rename_region_settingsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsdata',
            name='bulbPower',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='settingsdata',
            name='bulbType',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='settingsdata',
            name='numBulbs',
            field=models.IntegerField(default=1),
        ),
    ]
